version: "3.3"

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: blazor_test_user
      POSTGRES_PASSWORD: blazor_test_password
      POSTGRES_DB: blazor_test_db

volumes:
  data:
